### ISSUE TITLE
Small fixes to usage instructions: repl -> mrepl

### ISSUE THREAD

**Issue by ackalker** [qoocku/ac-sly#1]
There are two small errors in the usage instructions: Sly uses `mrepl` where SLIME uses `repl` in the names of variables.

A corrected, working configuration is:

``` elisp
(require 'ac-sly)
(add-hook 'sly-mode-hook 'set-up-sly-ac)
(add-hook 'sly-mrepl-mode-hook 'set-up-sly-ac)
(eval-after-load 'auto-complete
  '(add-to-list 'ac-modes 'sly-mrepl-mode))
```

Thanks for packaging :-)

**Comment by joaotavora** [comment]
I opened a pull request that should close this issue. `set-up-sly-ac` doesn't need to be added to `sly-mrepl-mode-hook` since the `mrepl` also turns on `sly-mode-hook`.

**Comment by ackalker** [comment]
Thanks for the quick responce :-)

> set-up-sly-ac doesn't need to be added to sly-mrepl-mode-hook since the mrepl also turns on sly-mode-hook.

So this is different from how SLIME's slime-repl-mode-hook works with ac-slime?

**Comment by joaotavora** [comment]
> So this is different from how SLIME's slime-repl-mode-hook works with ac-slime?

Yes. There is a `sly-mrepl-mode-hook`, but you don't need to use it in this particular situation because `sly-mrepl-mode` also turns on `sly-mode`.

**Comment by ackalker** [comment]
Ah, thanks for the explanation.

**Comment by joaotavora** [comment]
ping? There is a pull request that can be used to solve this and improve the instructions
